config/routes.rb
  get "/paypal/payment", to: "paypal#paypal_payment", as: "paypal_payment"
  get "/paypal/sign-in", to: "paypal#paypal_sign_in", as: "paypal_sign_in"
  get "/paypal/checkout", to: "paypal#paypal_order", as: "paypal_order"
  post "/paypal/checkout", to: "paypal#paypal_checkout", as: "paypal_checkout"
  post "/paypal/sign-in", to: "paypal#paypal_auth", as: "paypal_auth"
  # End PayPal

  # Pay upon delivery
  get "/pay-upon-delivery/checkout", to: "pay_upon_delivery#payment", as: "pay_upon_delivery_payment"
  post "/pay-upon-delivery/checkout", to: "pay_upon_delivery#checkout", as: "pay_upon_delivery_checkout"
  # End Pay upon delivery

  # Notifications
  get "/authentication/notifications", to: "authentication/notifications#index", as: "auth_notifications"
  # End Notifications

  # Customers
  get "/sign-up", to: "customers#new", as: "sign_up"
  get "/user", to: "customers#show", as: "customer"
  get "/user/edit", to: "customers#edit", as: "edit_customer"
  get "/users", to: redirect("/sign-up")
  post "/users", to: "customers#create", as: "customers"
  patch "/user", to: "customers#update", as: "update_customer"
  patch "/user/deactive", to: "customers#deactive", as: "deactive_customer"
  # End Customers

  # Users
  get "/user/update-password", to: "users#customer_update_password", as: "customer_update_password"
  patch "/user/update-password", to: "users#customer_change_password", as: "customer_change_password"
  # End Users

  # Sessions
  get "/sign-in", to: "authentication/sessions#new", as: "sign_in"
  get "/two-factor", to: "authentication/sessions#two_factor", as: "two_factor"
  post "/sign-in", to: "authentication/sessions#create", as: "sign_in_customer"
  post "/two-factor", to: "authentication/sessions#two_factor_auth", as: "two_factor_auth"
  patch "/resend-otp", to: "authentication/sessions#resend_otp", as: "resend_otp"
  delete "/sign-out", to: "authentication/sessions#destroy", as: "sign_out"
  # End Sessions

  # Confirmations
  get "/confirm-account", to: "authentication/confirmations#new", as: "confirm_account"
  get "/confirm-customer-account/:confirmation_token", to: "authentication/confirmations#show", as: "confirm_customer_account"
  post "/confirm-account", to: "authentication/confirmations#send_confirmation_email", as: "resend_confirmation"
  # End Confirmations

  # Unlocks
  get "/unlock-account", to: "authentication/unlocks#new", as: "unlock_account"
  get "/unlock-customer-account/:unlock_token", to: "authentication/unlocks#show", as: "unlock_customer_account"
  post "/unlock-account", to: "authentication/unlocks#send_unlock_email", as: "resend_unlock"
  # End Unlocks

  # Passwords
  get "/reset-password", to: "authentication/passwords#new", as: "reset_password"
  get "/reset-customer-password/:reset_password_token", to: "authentication/passwords#show", as: "reset_customer_password"
  post "/reset-password", to: "authentication/passwords#send_reset_password_email", as: "resend_reset_password"
  patch "/reset-customer-password", to: "authentication/passwords#update_password", as: "update_password"
  # End Passwords

  # End Authentications

  # Trackings
  get "/orders", to: "trackings#index", as: "orders"
  get "/tracking/:id", to: "trackings#show", as: "tracking"
  patch "/tracking/:id/confirm", to: "trackings#confirm_delivery", as: "confirm_delivery"
  # End Trackings

  # Invoices
  get "/invoice/:id", to: "invoices#show", as: "order_invoice"
  # End Invoices

  # Charts namespace
  namespace :charts do
    get "purchases-by-month", to: "purchases_by_month", as: "purchases_by_month"
    get "sales-by-month", to: "sales_by_month", as: "sales_by_month"

    get "sales-by-products", to: "sales_by_products", as: "sales_by_products"
    get "purchases-by-products", to: "purchases_by_products", as: "purchases_by_products"

    get "sales-by-customers", to: "sales_by_customers", as: "sales_by_customers"
    get "purchases-by-providers", to: "purchases_by_providers", as: "purchases_by_providers"

    get "sales-by-employees", to: "sales_by_employees", as: "sales_by_employees"
    get "purchases-by-employees", to: "purchases_by_employees", as: "purchases_by_employees"

    get "sales-by-categories", to: "sales_by_categories", as: "sales_by_categories"
    get "purchases-by-categories", to: "purchases_by_categories", as: "purchases_by_categories"

    get "products-by-categories", to: "products_by_categories", as: "products_by_categories"
  end
  # End Charts namespace

  # Admin namespace
  namespace :admin do
    # Root
    root "dashboard#index"
    # End Root

    # Authentications

    # Notifications
    get "/authentication/notifications", to: "authentication/notifications#index", as: "auth_notifications"
    # End Notifications

    # Sessions
    get "/sign-in", to: "authentication/sessions#new", as: "sign_in"
    get "/two-factor", to: "authentication/sessions#two_factor", as: "two_factor"
    post "/sign-in", to: "authentication/sessions#create", as: "sign_in_employee"
    post "/two-factor", to: "authentication/sessions#two_factor_auth", as: "two_factor_auth"
    patch "/resend-otp", to: "authentication/sessions#resend_otp", as: "resend_otp"
    delete "/sign-out", to: "authentication/sessions#destroy", as: "sign_out"
    # End Sessions

    # Confirmations
    get "/confirm-account", to: "authentication/confirmations#new", as: "confirm_account"
    get "/confirm-employee-account/:confirmation_token", to: "authentication/confirmations#show", as: "confirm_employee_account"
    post "/confirm-account", to: "authentication/confirmations#send_confirmation_email", as: "resend_confirmation"
    # End Confirmations

    # Unlocks
    get "/unlock-account", to: "authentication/unlocks#new", as: "unlock_account"
    get "/unlock-employee-account/:unlock_token", to: "authentication/unlocks#show", as: "unlock_employee_account"
    post "/unlock-account", to: "authentication/unlocks#send_unlock_email", as: "resend_unlock"
    # End Unlocks

    # Passwords
    get "/reset-password", to: "authentication/passwords#new", as: "reset_password"
    get "/reset-employee-password/:reset_password_token", to: "authentication/passwords#show", as: "reset_employee_password"
    post "/reset-password", to: "authentication/passwords#send_reset_password_email", as: "resend_reset_password"
    patch "/reset-employee-password", to: "authentication/passwords#update_password", as: "update_password"
    # End Passwords

    # End Authentications

    # Employees
    get "/employees", to: "employees#index", as: "employees"
    get "/employee/new", to: "employees#new", as: "new_employee"
    get "/employee/:id", to: "employees#show", as: "employee"
    get "/employee/:id/edit", to: "employees#edit", as: "edit_employee"
    get "/employee/:id/history", to: "employees#history", as: "history_employee"
    post "/employees", to: "employees#create"
    patch "/employee/:id", to: "employees#update", as: "update_employee"
    patch "/employees/:id/active", to: "employees#active", as: "active_employee"
    patch "/employees/:id/deactive", to: "employees#deactive", as: "deactive_employee"
    # End Employees

    # Employees/Users
    get "/employee/:id/create-user", to: "users#new_employee_user", as: "new_employee_user"
    get "/employee/:id/update-password", to: "users#employee_update_password", as: "update_password_employee"
    post "/employee/:id/create-user", to: "users#create_employee_user", as: "create_employee_user"
    patch "/employee/:id/update-password", to: "users#employee_change_password", as: "change_password_employee"
    # End Employees/Users

    # Providers
    get "/providers", to: "providers#index", as: "providers"
    get "/provider/new", to: "providers#new", as: "new_provider"
    get "/provider/:id", to: "providers#show", as: "provider"
    get "/provider/:id/edit", to: "providers#edit", as: "edit_provider"
    get "/provider/:id/history", to: "providers#history", as: "history_provider"
    post "/providers", to: "providers#create"
    patch "/provider/:id", to: "providers#update", as: "update_provider"
    patch "/providers/:id/active", to: "providers#active", as: "active_provider"
    patch "/providers/:id/deactive", to: "providers#deactive", as: "deactive_provider"
    # End Providers

    # Customers
    get "/customers", to: "customers#index", as: "customers"
    get "/customer/new", to: "customers#new", as: "new_customer"
    get "/customer/:id", to: "customers#show", as: "customer"
    get "/customer/:id/edit", to: "customers#edit", as: "edit_customer"
    get "/customer/:id/history", to: "customers#history", as: "history_customer"
    post "/customers", to: "customers#create"
    patch "/customer/:id", to: "customers#update", as: "update_customer"
    patch "/customers/:id/active", to: "customers#active", as: "active_customer"
    patch "/customers/:id/deactive", to: "customers#deactive", as: "deactive_customer"
    # End Customers

    # Customers/Users
    get "/customer/:id/create-user", to: "users#new_customer_user", as: "new_customer_user"
    get "/customer/:id/update-password", to: "users#customer_update_password", as: "update_password_customer"
    post "/customer/:id/create-user", to: "users#create_customer_user", as: "create_customer_user"
    patch "/customer/:id/update-password", to: "users#customer_change_password", as: "change_password_customer"
    # End Customers/Users

    # Categories
    get "/categories", to: "categories#index", as: "categories"
    get "/category/new", to: "categories#new", as: "new_category"
    get "/category/:id", to: "categories#show", as: "category"
    get "/category/:id/edit", to: "categories#edit", as: "edit_category"
    get "/category/:id/history", to: "categories#history", as: "history_category"
    post "/categories", to: "categories#create"
    patch "/category/:id", to: "categories#update", as: "update_category"
    patch "/categories/:id/active", to: "categories#active", as: "active_category"

app/models/sale.rb
class Sale < ApplicationRecord
  # Associations
  belongs_to :customer
  belongs_to :employee
  has_many :sale_details, inverse_of: :sale
  # End Associations

  # Nested attributes
  accepts_nested_attributes_for :sale_details, reject_if: :all_blank, allow_destroy: true
  # End Nested attributes

  # Audit
  has_associated_audits
  audited
  # End Audit

  # Render sync
  sync :all
  # sync_touch :sale_details
  # End Render sync

  # Search order e-commerce
  def self.search_order_ecommerce(search, customer_id)
    if search
      self.joins(:customer).joins(:employee).where("(DATE_FORMAT(sale_datetime, '%d/%m/%Y') LIKE :search OR DATE_FORMAT(sale_datetime, '%m/%d/%Y') LIKE :search OR payment_method LIKE :search OR payment_reference LIKE :search OR delivery_status LIKE :search) AND (status != 'invoiced') AND (sales.customer_id = :customer_id)", customer_id: customer_id, search: "%#{search}%").order("sales.sale_datetime DESC")

    else
      self.where("sales.customer_id = :customer_id", customer_id: customer_id).not_invoices.order("sales.sale_datetime DESC")
    end
  end
  # End Search order e-commerce

  # Search order
  def self.search_order(search, show_all)
    if search
      self.joins(:customer).joins(:employee).where("(DATE_FORMAT(sale_datetime, '%d/%m/%Y') LIKE :search OR DATE_FORMAT(sale_datetime, '%m/%d/%Y') LIKE :search OR customers.first_name LIKE :search OR customers.last_name LIKE :search OR customers.company LIKE :search OR employees.first_name LIKE :search OR employees.last_name LIKE :search) AND (status = 'ordered')", search: "%#{search}%").order("sales.sale_datetime DESC")

    elsif show_all == "all"
      orders.order("sales.sale_datetime DESC")

    else
      orders.enabled.order("sales.sale_datetime DESC")
    end
  end
  # End Search order

  # Search invoice
  def self.search_invoice(search, show_all)
    if search
      self.joins(:customer).joins(:employee).where("(DATE_FORMAT(sale_datetime, '%d/%m/%Y') LIKE :search OR DATE_FORMAT(sale_datetime, '%m/%d/%Y') LIKE :search OR customers.first_name LIKE :search OR customers.last_name LIKE :search OR customers.company LIKE :search OR employees.first_name LIKE :search OR employees.last_name LIKE :search) AND (status = 'invoiced')", search: "%#{search}%").order("sales.sale_datetime DESC")

    elsif show_all == "all"
      invoices.order("sales.sale_datetime DESC")

    else
      invoices.enabled.order("sales.sale_datetime DESC")
    end
  end
  # End Search invoice

  # Search shipment
  def self.search_shipment(search, show_all)
    if search
      self.joins(:customer).joins(:employee).where("(DATE_FORMAT(sale_datetime, '%d/%m/%Y') LIKE :search OR DATE_FORMAT(sale_datetime, '%m/%d/%Y') LIKE :search OR customers.first_name LIKE :search OR customers.last_name LIKE :search OR customers.company LIKE :search OR employees.first_name LIKE :search OR employees.last_name LIKE :search) AND (status = 'shipped')", search: "%#{search}%").order("sales.sale_datetime DESC")

    elsif show_all == "all"
      shipments.order("sales.sale_datetime DESC")

    else
      shipments.enabled.order("sales.sale_datetime DESC")
    end
  end
  # End Search shipment

  # Search delivery
  def self.search_delivery(search, show_all)
    if search
      self.joins(:customer).joins(:employee).where("(DATE_FORMAT(sale_datetime, '%d/%m/%Y') LIKE :search OR DATE_FORMAT(sale_datetime, '%m/%d/%Y') LIKE :search OR customers.first_name LIKE :search OR customers.last_name LIKE :search OR customers.company LIKE :search OR employees.first_name LIKE :search OR employees.last_name LIKE :search) AND (status = 'delivered')", search: "%#{search}%").order("sales.sale_datetime DESC")

    elsif show_all == "all"
      deliveries.order("sales.sale_datetime DESC")

    else
      deliveries.enabled.order("sales.sale_datetime DESC")
    end
  end
  # End Search delivery

  # Search price list
  def self.search_price_list(search, show_all)
    if search
      self.joins(:customer).joins(:employee).where("(DATE_FORMAT(sale_datetime, '%d/%m/%Y') LIKE :search OR DATE_FORMAT(sale_datetime, '%m/%d/%Y') LIKE :search OR customers.first_name LIKE :search OR customers.last_name LIKE :search OR customers.company LIKE :search OR employees.first_name LIKE :search OR employees.last_name LIKE :search) AND (status = 'price_list')", search: "%#{search}%").order("sales.sale_datetime DESC")

    else
      price_lists.order("sales.sale_datetime DESC")
    end
  end
  # End Search price list

  # Total
  def self.total(id)
    self.find(id).sale_details.not_returned.sum("price * quantity")
  end
  # End Total

  # Presence validation
  validates :customer_id, presence: true
  validates :employee_id, presence: true
  validates :sale_datetime, presence: true
  validates :discount, presence: true
  validates :payment_method, presence: true
  validates :payment_reference, presence: true
  # validates :paid, presence: true
  # End  Presence validation

  # Length validation
  validates :delivery_status, length: { maximum: 255 }
  validates :status, length: { maximum: 255 }
  validates :payment_method, length: { maximum: 255 }
  validates :payment_reference, length: { maximum: 255 }
  validates :observations, length: { maximum: 255 }, allow_blank: true
  # End Length validation

  # Numericality validation
  # validates :discount, numericality: {greater_than_or_equal_to: 0, less_than: 100}
  # End Numericality validation

  ## Scopes
  scope :not_invoices, -> { where("(sales.status != 'invoiced')") }
  scope :enabled, -> { where(state: true) }
  scope :orders, -> { where(status: "ordered") }
  scope :invoices, -> { where(status: "invoiced") }
  scope :shipments, -> { where(status: "shipped") }
  scope :deliveries, -> { where(status: "delivered") }
  scope :price_lists, -> { where(status: "price_list") }
  ## End Scopes

  ## Callbacks

  # # Before destroy
  # before_destroy :not_permit_destroy
  #
  # # Before_destroy callback, avoid destroy information
  # def not_permit_destroy
  #   false
  # end

  ## End Callbacks
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  # Ecommerce layout
  layout "application_ecommerce"
  # End Ecommerce layout

  # Find sale
  before_action :set_sale, only: [:show]
  # End Find sale

  # Authentication
  before_action :require_customer
  # End Authentication

  def show
    # PDF view configuration
    current_lang = params[:lang]
    I18n.locale = current_lang

    datetime =  Time.zone.now
    file_time = datetime.strftime("%m%d%Y")

    name_pdf = "BANP-invoice-#{@sale.id}-#{file_time}"
    # template = "admin/sale_details/show_pdf.html.haml"

    if @is_invoice
      title_pdf = "#{t('sale.invoice_details')} ##{@sale.id}"

    elsif @is_shipment
      title_pdf = "#{t('sale.shipment_details')} ##{@sale.id}"

    elsif @is_delivery
      title_pdf = "#{t('sale.delivery_details')} ##{@sale.id}"

    else
      title_pdf = "#{t('sale.order_details')} ##{@sale.id}"
    end
    # End PDF view configuration

    @invoice_no = @sale.id
    @invoice_date = @sale.sale_datetime
    template = "partials/invoice.html.haml"

    respond_to do |format|
      format.pdf do
        # to_pdf(name_pdf, template, @details, I18n.l(datetime), title_pdf)
        invoice_pdf_download(name_pdf, template, @sale, I18n.l(datetime), title_pdf)
      end
    end
  end

  private

  # Set Sale
  def set_sale
    @sale = Sale.find(params[:id])

  rescue
    redirect_to root_orders_path, alert: t("alerts.not_found", model: t("activerecord.models.sale"))
  end
end

app/helpers/admin/sales/invoices_helper.rb
module Admin::Sales::InvoicesHelper
end

app/helpers/admin/sales/orders_helper.rb
module Admin::Sales::OrdersHelper
end

app/helpers/admin/sales_helper.rb
module Admin::SalesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/sync/sales/invoices/_data_breadcrumb.html.haml
.row
  .col-xs-12.hidden-xs
    .breadcrumb-container
      %ol.breadcrumb
        %li
          = link_to (admin_root_path) do
            %i.fas.fa-tachometer-alt
            %span= t("header.navigation.dashboard")
        %li
          = link_to (admin_sale_invoices_path) do
            %i.far.fa-newspaper
            %span= t("sale.invoices")
        %li.active
          %i.fas.fa-list-alt
          = "#{@count == 1 ? t('sale.invoice_detail') : t('sale.invoice_details')} ##{sale.id}"

app/views/sync/sales/invoices/_data_details.html.haml
.general-info
  .main-info
    %p= I18n.l(sale.sale_datetime, format: I18n.locale == :es ? "%A, %d #{t('sale.of')} %B #{t('sale.of')} %Y" : "%A, %B %d, %Y").capitalize
    %p= I18n.l(sale.sale_datetime, format: "%I:%M:%S %p").capitalize

  %br

  %div{class: "main-info text-left-right paid #{'not-paid' if !sale.paid}"}
    %p.text-left
      %b
        %i.fas.fa-hand-holding-usd
        %span= t("activerecord.attributes.sale.paid")

    %p.text-right= sale.paid ? "Si" : "No"

  .main-info.text-left-right
    %p.text-left
      %b
        - if sale.payment_method == "cash"
          %i.fas.fa-money-bill-alt

        - elsif sale.payment_method == "card"
          %i.fas.fa-credit-card

        - elsif sale.payment_method == "PayPal"
          %i.fab.fa-paypal

        - elsif sale.payment_method == "Stripe"
          %i.fab.fa-stripe-s

        - else
          %i.fas.fa-dollar-sign

        %span= t("activerecord.attributes.sale.payment_method")

    %p.text-right
      - if sale.payment_method == "cash"
        = t("sale.cash")

      - elsif sale.payment_method == "card"
        = t("sale.cash")

      - else
        = sale.payment_method

  .main-info
    %p.text-center
      %b
        %i.fas.fa-file-invoice
        %span= t("activerecord.attributes.sale.payment_reference")
    %p.text-center= sale.payment_reference

  %br

  .main-info.text-left-right
    %p.text-left
      %b
        %i.fas.fa-users
        %span= t("activerecord.models.customer")
    -# Customer name render_sync
    = sync partial: "detail_customer_name", resource: sale.customer
    = sync_new partial: "detail_customer_name", resource: Customer.new
    -# End Customer name render_sync

  .main-info.text-left-right
    %p.text-left
      %b
        %i.fas.fa-briefcase
        %span= t("activerecord.models.employee")
    -# Employee name render_sync
    = sync partial: "detail_employee_name", resource: sale.employee
    = sync_new partial: "detail_employee_name", resource: Employee.new
    -# End Employee name render_sync

  .main-info
    %p.text-center
      %b
        %i.fas.fa-list-alt
        %span= t("activerecord.attributes.sale.observations")
    %p.text-center= sale.observations

  %br

  .main-info.text-left-right
    %p.text-left
      %b Subtotal
    %p.text-right= "#{number_to_currency(Sale.total(sale.id), precision: 2, unit: '$', format: '%u%n', separator: '.', delimiter: ',')}"

  .main-info.text-left-right
    %p.text-left
      %b= "#{t('activerecord.attributes.sale.discount')} (#{sale.discount}%)"
    %p.text-right="- #{number_to_currency((Sale.total(sale.id) * (sale.discount / 100)), precision: 2, unit: '$', format: '%u%n', separator: '.', delimiter: ',')}"

  .main-info.text-left-right
    .divider

  .main-info.text-left-right
    %p.text-left.total
      %b Total
    %p.text-right.total= number_to_currency((Sale.total(sale.id) - (Sale.total(sale.id) * (sale.discount / 100))), precision: 2, unit: "$", format: "%u%n", separator: ".", delimiter: ",")

  .main-info
    %p= t("views.show.created_at", time: time_ago_in_words(sale.created_at))
    %p= t("views.show.updated_at", time: time_ago_in_words(sale.updated_at))

  .main-buttons
    - if sale.state
      .col-xs-12.col-sm-4.col-md-6.button-container.no-padding
        = link_to (admin_edit_sale_invoice_path(sale)), class: "btn btn-general" do
          %i.fas.fa-edit
          %span= t("views.show.edit")


    %div{class: " col-xs-12 col-sm-4 col-md-6 #{'col-md-offset-3' if !sale.state} button-container no-padding"}
      = link_to (admin_history_sale_invoice_path(sale)), class: "btn btn-general" do
        %i.fas.fa-history
        %span= t("views.show.history")

    .col-xs-12.col-sm-4.col-md-12.button-container.no-padding
      - if sale.state
        = link_to (admin_deactive_sale_invoice_path(sale)), method: "patch", class: "btn btn-general" do
          %i.fas.fa-times
          %span= t("views.show.cancel")

app/views/sync/sales/invoices/_data_table.html.haml
%tr{class: "clickable-row #{sale.state}", "data-href": "#{admin_sale_details_path(sale.id)}"}
  -# Set attributes
  - attributes = ["sale_datetime", "total", "customer", "employee", "paid", "payment_method", "delivery_status"]

  %td
    = link_to admin_sale_details_path(sale.id), class: "record-link", "data-header": "No.", "data-toggle": "tooltip", "data-placement": "bottom", title: t("views.index.view_details") do
      %p= sale.id

  - attributes.each do |attribute|
    %td
      = link_to admin_sale_details_path(sale.id), class: "record-link", "data-header": t("activerecord.attributes.sale.#{attribute}"), "data-toggle": "tooltip", "data-placement": "bottom", title: t("views.index.view_details") do
        - if attribute == "sale_datetime"
          -# %p= I18n.l(sale["#{attribute}"], format: :short)
          %p= I18n.locale == :es ? sale.sale_datetime.strftime("%d/%m/%Y") : sale.sale_datetime.strftime("%m/%d/%Y")

        - elsif attribute == "total"
          %p= number_to_currency((Sale.total(sale.id) - (Sale.total(sale.id) * (sale.discount / 100))), precision: 2, unit: '$', format: '%u%n', separator: '.', delimiter: ',')

        - elsif attribute == "customer"
          -# Customer name render_sync
          = sync partial: "data_table_customer_name", resource: sale.customer
          = sync_new partial: "data_table_customer_name", resource: Customer.new
          -# End Customer name render_sync

        - elsif attribute == "employee"
          -# Employee name render_sync
          = sync partial: "data_table_employee_name", resource: sale.employee
          = sync_new partial: "data_table_employee_name", resource: Employee.new
          -# End Employee name render_sync

        - elsif attribute == "paid"
          - if sale["#{attribute}"]
            = I18n.locale == :es ? "Si" : "Yes"

          - else
            = "No"

        - elsif attribute == "payment_method"
          - if sale["#{attribute}"] == "cash"
            = I18n.locale == :es ? "Efectivo" : "Cash"

          - elsif sale["#{attribute}"] == "card"
            = I18n.locale == :es ? "Tarjeta" : "Card"

          - else
            = sale["#{attribute}"]

        - elsif attribute == "delivery_status"
          %p
            - if sale["#{attribute}"] == "in_queue"
              = I18n.locale == :es ? "En espera" : "In queue"

            - elsif sale["#{attribute}"] == "received"
              = I18n.locale == :es ? "Recibido" : "Received"

            - elsif sale["#{attribute}"] == "shipped"
              = I18n.locale == :es ? "Enviado" : "Shipped"

            - elsif sale["#{attribute}"] == "delivered"
              = I18n.locale == :es ? "Entregado" : "Delivered"

            - elsif sale["#{attribute}"] == "returned"
              = I18n.locale == :es ? "Devuelto" : "Returned"

        - else
          %p= sale["#{attribute}"]