config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Change language
  get "/change-language/:lang", to: "settings#change_lang", as: "change_language"
  # End Change language

  # Errors pages
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  # Root
  root "landing#index"
  # End Root

  # Products
  get "/products", to: "products#index", as: "products"
  get "/product/:id", to: "products#show", as: "product"
  # End Products

  # Authentications

  # Cart
  get "/cart", to: "cart#index", as: "cart"
  # End Cart

  # Stripe
  get "/stripe/checkout", to: "stripe#payment", as: "stripe_payment"
  post "/stripe/checkout", to: "stripe#checkout", as: "stripe_checkout"
  # End Stripe

  # PayPal
  get "/paypal/payment", to: "paypal#paypal_payment", as: "paypal_payment"
  get "/paypal/sign-in", to: "paypal#paypal_sign_in", as: "paypal_sign_in"
  get "/paypal/checkout", to: "paypal#paypal_order", as: "paypal_order"
  post "/paypal/checkout", to: "paypal#paypal_checkout", as: "paypal_checkout"
  post "/paypal/sign-in", to: "paypal#paypal_auth", as: "paypal_auth"
  # End PayPal

  # Pay upon delivery
  get "/pay-upon-delivery/checkout", to: "pay_upon_delivery#payment", as: "pay_upon_delivery_payment"
  post "/pay-upon-delivery/checkout", to: "pay_upon_delivery#checkout", as: "pay_upon_delivery_checkout"
  # End Pay upon delivery

  # Notifications
  get "/authentication/notifications", to: "authentication/notifications#index", as: "auth_notifications"
  # End Notifications

  # Customers
  get "/sign-up", to: "customers#new", as: "sign_up"
  get "/user", to: "customers#show", as: "customer"
  get "/user/edit", to: "customers#edit", as: "edit_customer"
  get "/users", to: redirect("/sign-up")
  post "/users", to: "customers#create", as: "customers"
  patch "/user", to: "customers#update", as: "update_customer"
  patch "/user/deactive", to: "customers#deactive", as: "deactive_customer"
  # End Customers

  # Users
  get "/user/update-password", to: "users#customer_update_password", as: "customer_update_password"
  patch "/user/update-password", to: "users#customer_change_password", as: "customer_change_password"
  # End Users

  # Sessions
  get "/sign-in", to: "authentication/sessions#new", as: "sign_in"
  get "/two-factor", to: "authentication/sessions#two_factor", as: "two_factor"
  post "/sign-in", to: "authentication/sessions#create", as: "sign_in_customer"
  post "/two-factor", to: "authentication/sessions#two_factor_auth", as: "two_factor_auth"
  patch "/resend-otp", to: "authentication/sessions#resend_otp", as: "resend_otp"
  delete "/sign-out", to: "authentication/sessions#destroy", as: "sign_out"
  # End Sessions

  # Confirmations
  get "/confirm-account", to: "authentication/confirmations#new", as: "confirm_account"
  get "/confirm-customer-account/:confirmation_token", to: "authentication/confirmations#show", as: "confirm_customer_account"
  post "/confirm-account", to: "authentication/confirmations#send_confirmation_email", as: "resend_confirmation"
  # End Confirmations

  # Unlocks
  get "/unlock-account", to: "authentication/unlocks#new", as: "unlock_account"
  get "/unlock-customer-account/:unlock_token", to: "authentication/unlocks#show", as: "unlock_customer_account"
  post "/unlock-account", to: "authentication/unlocks#send_unlock_email", as: "resend_unlock"
  # End Unlocks

  # Passwords
  get "/reset-password", to: "authentication/passwords#new", as: "reset_password"
  get "/reset-customer-password/:reset_password_token", to: "authentication/passwords#show", as: "reset_customer_password"
  post "/reset-password", to: "authentication/passwords#send_reset_password_email", as: "resend_reset_password"
  patch "/reset-customer-password", to: "authentication/passwords#update_password", as: "update_password"
  # End Passwords

  # End Authentications

  # Trackings
  get "/orders", to: "trackings#index", as: "orders"
  get "/tracking/:id", to: "trackings#show", as: "tracking"
  patch "/tracking/:id/confirm", to: "trackings#confirm_delivery", as: "confirm_delivery"
  # End Trackings

  # Invoices
  get "/invoice/:id", to: "invoices#show", as: "order_invoice"
  # End Invoices

  # Charts namespace
  namespace :charts do
    get "purchases-by-month", to: "purchases_by_month", as: "purchases_by_month"
    get "sales-by-month", to: "sales_by_month", as: "sales_by_month"

    get "sales-by-products", to: "sales_by_products", as: "sales_by_products"
    get "purchases-by-products", to: "purchases_by_products", as: "purchases_by_products"

    get "sales-by-customers", to: "sales_by_customers", as: "sales_by_customers"
    get "purchases-by-providers", to: "purchases_by_providers", as: "purchases_by_providers"

    get "sales-by-employees", to: "sales_by_employees", as: "sales_by_employees"
    get "purchases-by-employees", to: "purchases_by_employees", as: "purchases_by_employees"

    get "sales-by-categories", to: "sales_by_categories", as: "sales_by_categories"
    get "purchases-by-categories", to: "purchases_by_categories", as: "purchases_by_categories"

    get "products-by-categories", to: "products_by_categories", as: "products_by_categories"
  end
  # End Charts namespace

  # Admin namespace
  namespace :admin do
    # Root
    root "dashboard#index"
    # End Root

    # Authentications

    # Notifications
    get "/authentication/notifications", to: "authentication/notifications#index", as: "auth_notifications"
    # End Notifications

    # Sessions
    get "/sign-in", to: "authentication/sessions#new", as: "sign_in"
    get "/two-factor", to: "authentication/sessions#two_factor", as: "two_factor"
    post "/sign-in", to: "authentication/sessions#create", as: "sign_in_employee"
    post "/two-factor", to: "authentication/sessions#two_factor_auth", as: "two_factor_auth"
    patch "/resend-otp", to: "authentication/sessions#resend_otp", as: "resend_otp"
    delete "/sign-out", to: "authentication/sessions#destroy", as: "sign_out"
    # End Sessions

    # Confirmations
    get "/confirm-account", to: "authentication/confirmations#new", as: "confirm_account"
    get "/confirm-employee-account/:confirmation_token", to: "authentication/confirmations#show", as: "confirm_employee_account"
    post "/confirm-account", to: "authentication/confirmations#send_confirmation_email", as: "resend_confirmation"
    # End Confirmations

    # Unlocks
    get "/unlock-account", to: "authentication/unlocks#new", as: "unlock_account"
    get "/unlock-employee-account/:unlock_token", to: "authentication/unlocks#show", as: "unlock_employee_account"
    post "/unlock-account", to: "authentication/unlocks#send_unlock_email", as: "resend_unlock"
    # End Unlocks

    # Passwords
    get "/reset-password", to: "authentication/passwords#new", as: "reset_password"
    get "/reset-employee-password/:reset_password_token", to: "authentication/passwords#show", as: "reset_employee_password"
    post "/reset-password", to: "authentication/passwords#send_reset_password_email", as: "resend_reset_password"
    patch "/reset-employee-password", to: "authentication/passwords#update_password", as: "update_password"
    # End Passwords

    # End Authentications

    # Employees
    get "/employees", to: "employees#index", as: "employees"
    get "/employee/new", to: "employees#new", as: "new_employee"
    get "/employee/:id", to: "employees#show", as: "employee"
    get "/employee/:id/edit", to: "employees#edit", as: "edit_employee"
    get "/employee/:id/history", to: "employees#history", as: "history_employee"
    post "/employees", to: "employees#create"
    patch "/employee/:id", to: "employees#update", as: "update_employee"
    patch "/employees/:id/active", to: "employees#active", as: "active_employee"
    patch "/employees/:id/deactive", to: "employees#deactive", as: "deactive_employee"
    # End Employees

    # Employees/Users
    get "/employee/:id/create-user", to: "users#new_employee_user", as: "new_employee_user"
    get "/employee/:id/update-password", to: "users#employee_update_password", as: "update_password_employee"
    post "/employee/:id/create-user", to: "users#create_employee_user", as: "create_employee_user"
    patch "/employee/:id/update-password", to: "users#employee_change_password", as: "change_password_employee"
    # End Employees/Users

    # Providers
    get "/providers", to: "providers#index", as: "providers"
    get "/provider/new", to: "providers#new", as: "new_provider"
    get "/provider/:id", to: "providers#show", as: "provider"
    get "/provider/:id/edit", to: "providers#edit", as: "edit_provider"
    get "/provider/:id/history", to: "providers#history", as: "history_provider"
    post "/providers", to: "providers#create"
    patch "/provider/:id", to: "providers#update", as: "update_provider"
    patch "/providers/:id/active", to: "providers#active", as: "active_provider"
    patch "/providers/:id/deactive", to: "providers#deactive", as: "deactive_provider"
    # End Providers

    # Customers
    get "/customers", to: "customers#index", as: "customers"
    get "/customer/new", to: "customers#new", as: "new_customer"
    get "/customer/:id", to: "customers#show", as: "customer"
    get "/customer/:id/edit", to: "customers#edit", as: "edit_customer"
    get "/customer/:id/history", to: "customers#history", as: "history_customer"
    post "/customers", to: "customers#create"
    patch "/customer/:id", to: "customers#update", as: "update_customer"
    patch "/customers/:id/active", to: "customers#active", as: "active_customer"
    patch "/customers/:id/deactive", to: "customers#deactive", as: "deactive_customer"
    # End Customers

    # Customers/Users
    get "/customer/:id/create-user", to: "users#new_customer_user", as: "new_customer_user"

app/views/layouts/admin/_flash-alert.html.haml
- if !flash[:alert].blank?
  .alert.alert-danger.alert-dismissible.shadow-card{role: "alert"}
    %button.close{"data-dismiss": "alert", type: "button", "data-toggle": "tooltip", "data-placement": "top", title: t("views.form.close")}
      %span
        %i.fas.fa-times-circle
    %strong
      %p
        %i.fas.fa-exclamation-triangle
        = flash[:alert]

app/views/layouts/admin/_flash-notice.html.haml
- if !flash[:notice].blank?
  .alert.alert-success.alert-dismissible.shadow-card{role: "alert"}
    %button.close{"data-dismiss": "alert", type: "button", "data-toggle": "tooltip", "data-placement": "top", title: t("views.form.close")}
      %span
        %i.fas.fa-times-circle
    %strong
      %p
        %i.fas.fa-info-circle
        = flash[:notice]

app/views/layouts/admin/_footer.html.haml
.fix-footer

%footer
  %section.footer-top
    .container-fluid
      .row
        .col-xs-12.col-sm-1.image-container
          .footer-legal
            = image_tag "img/usda-organic.png", class: "img-responsive hidden-xs", alt: "USDA Organic"
            = image_tag "img/usda-organic-mobile.png", class: "img-responsive visible-xs", alt: "USDA Organic"

        .col-xs-12.col-sm-7
          .footer-legal
            %p
              %span
                © #{Time.now.year}
              %span
                Better and Nice Produce Corp.
                %span Miami, Florida

        -# Setting client attributes
        - client = DeviceDetector.new(request.user_agent)
        - client_ip = request.remote_ip
        - client_browser = client.name
        - client_os = "#{client.os_name} #{client.os_full_version}"
        - client_device = client.device_name
        - client_country = Geocoder.search(client_ip).first.country

        .col-xs-12.col-sm-4
          .footer-legal
            %p.request-info
              %span= client.known? ? "#{client_device} #{client_browser} #{client_os} @ #{client_ip} | #{client_country}" : "#{client_ip} | #{client_country}"

app/views/layouts/admin/_header.html.haml
%body
  %header#back-top.header-top.navbar-fixed-top{"data-custom-affix": "1", role: "navigation"}
    %section.top-navbar
      .container-fluid.header-options
        .navbar-brand-top
          .row.navbar-brand-row
            .col-xs-12.col-sm-4.col-md-6.hidden-xs
              -# Logo tablet and mobile
              .logo-top
                = link_to (admin_root_path) do
                  %p.banp-logo BANP

            .col-xs-12.col-sm-8.col-md-6
              -# Settings container
              .settings-container
                -# Render languages
                = render "layouts/admin/languages"
                -# End Render languages

                -# Render notifications
                = render "layouts/admin/notifications"
                -# End Render notifications

                -# Render user
                = render "layouts/admin/user"
                -# End Render user

      -# Navbar default
      %nav.navbar.navbar-default{role: "navigation"}
        .container
          -# Navbar mobile
          .navbar-header
            -# Navbar toggle
            %button.navbar-toggle.collapsed{"aria-expanded": "false", "data-target": "#navbar", "data-toggle": "collapse", type: "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar.top-bar
              %span.icon-bar.middle-bar
              %span.icon-bar.bottom-bar

            -# Logo mobile
            = link_to (admin_root_path), class: "navbar-brand visible-xs" do
              %p.banp-logo BANP

          -# Render navigation
          = render "layouts/admin/navigation"
          -# End Render navigation

app/views/layouts/admin/_languages.html.haml
.language-container
  .dropdown
    %a.custom-btn.dropdown-toggle{"data-toggle": "dropdown", href: "#", "data-tooltip": "true", "data-placement": "left", title: t("views.navigation.language")}
      %i.fas.fa-language
    %ul.dropdown-menu
      %li
        = link_to (change_language_path(:en)), class: "#{'active' if I18n.locale.to_s == 'en'}" do
          %span.flag-icon.flag-icon-us
          %span English
      %li
        = link_to (change_language_path(:es)), class: "#{'active' if I18n.locale.to_s == 'es'}" do
          %span.flag-icon.flag-icon-es
          %span Español

app/views/layouts/admin/_navigation.html.haml
#navbar.collapse.navbar-collapse
  %ul.nav.navbar-nav
    - if current_employee.is_administrator?
      -# Dashboard
      %li
        = link_to (admin_root_path) do
          %i.fas.fa-tachometer-alt
          = t("header.navigation.dashboard")
      -# End Dashboard

    - if current_employee.is_administrator? || current_employee.is_warehouse_supervisor?
      -# Providers
      %li
        = link_to (admin_providers_path), class: "#{'active' if controller_name == 'providers'}" do
          %i.fas.fa-building
          %span= t("header.navigation.providers")
      -# End Providers

    - if current_employee.is_administrator? || current_employee.is_seller?
      -# Customers
      %li
        = link_to (admin_customers_path), class: "#{'active' if controller_name == 'customers'}" do
          %i.fas.fa-users
          %span= t("header.navigation.customers")
      -# End Customers

    - if current_employee.is_administrator? || current_employee.is_warehouse_supervisor? || current_employee.is_seller?
      -# Catalog
      %li.dropdown
        %a{class: "dropdown-toggle #{'active' if (controller_name == 'categories' or controller_name == 'products')}", "data-toggle": "dropdown", href: "#"}
          %i.fas.fa-list-alt
          = t("header.navigation.catalog")
          %i.fas.fa-caret-down

        %ul.dropdown-menu
          -# Categories
          %li
            = link_to (admin_categories_path), class: "#{'active' if controller_name == 'categories'}" do
              %i.fas.fa-tags
              %span= t("header.navigation.categories")
          -# End categories

          -# Products
          %li
            = link_to (admin_products_path), class: "#{'active' if controller_name == 'products'}" do
              %i.fas.fa-cubes
              %span= t("header.navigation.products")
          -# End Products
      -# End Catalog

    - if current_employee.is_administrator? || current_employee.is_warehouse_supervisor? || current_employee.is_seller?
      -# Purchases
      %li.dropdown
        %a.dropdown-toggle{"data-toggle": "dropdown", href: "#"}
          %i.fas.fa-shopping-bag
          = t("header.navigation.purchases")
          %i.fas.fa-caret-down

        %ul.dropdown-menu
          - if current_employee.is_administrator? || current_employee.is_warehouse_supervisor?
            -# Orders
            %li
              = link_to (admin_purchase_orders_path), class: "#{'active' if (controller_name == 'purchases' && action_name == 'index_orders')}" do
                %i.far.fa-newspaper
                = t("header.navigation.orders")
            -# End Orders

            -# Receptions
            %li
              = link_to (admin_purchase_receptions_path), class: "#{'active' if (controller_name == 'purchases' && action_name == 'index_receptions')}" do
                %i.fas.fa-cart-arrow-down
                = t("header.navigation.receptions")
            -# End Receptions

          - if current_employee.is_administrator? || current_employee.is_warehouse_supervisor? || current_employee.is_seller?
            -# Inventory
            %li
              = link_to (admin_inventory_path), class: "#{'active' if controller_name == 'inventories'}" do
                %i.fas.fa-archive
                = t("header.navigation.inventory")
            -# End Inventory
          - if current_employee.is_administrator? || current_employee.is_warehouse_supervisor?
            -# Returns
            %li
              = link_to (admin_purchase_returns_path), class: "#{'active' if (controller_name == 'purchases' && action_name == 'index_returns')}" do
                %i.fas.fa-undo
                = t("header.navigation.returns")
            -# End Returns
      -# End Purchases

    - if current_employee.is_administrator? || current_employee.is_seller? || current_employee.is_driver?
      -# Sales
      %li.dropdown
        %a.dropdown-toggle{"data-toggle": "dropdown", href: "#"}
          %i.fas.fa-shopping-cart
          = t("header.navigation.sales")
          %i.fas.fa-caret-down

        %ul.dropdown-menu
          - if current_employee.is_administrator? || current_employee.is_seller?
            -# Orders
            %li
              = link_to (admin_sale_orders_path), class: "#{'active' if (controller_name == 'sales' && action_name == 'index_orders')}" do
                %i.far.fa-newspaper
                = t("header.navigation.orders")
            -# End Orders

          - if current_employee.is_administrator? || current_employee.is_seller?
            -# Invoices
            %li
              = link_to (admin_sale_invoices_path), class: "#{'active' if (controller_name == 'sales' && (action_name == 'index_invoices' || action_name == 'new_invoice'))}" do
                %i.fas.fa-cart-plus
                = t("header.navigation.invoicing")
            -# End Invoices

          - if current_employee.is_administrator? || current_employee.is_seller? || current_employee.is_driver?
            -# Shipments
            %li
              = link_to (admin_sale_shipments_path), class: "#{'active' if (controller_name == 'sales' && action_name == 'index_shipments')}" do
                %i.fas.fa-truck
                = t("header.navigation.shipments")
            -# End Shipments

          - if current_employee.is_administrator? || current_employee.is_seller? || current_employee.is_driver?
            -# Deliveries
            %li
              = link_to (admin_sale_deliveries_path), class: "#{'active' if (controller_name == 'sales' && action_name == 'index_deliveries')}" do
                %i.fas.fa-box-open
                = t("header.navigation.deliveries")
            -# End Deliveries

          - if current_employee.is_administrator? || current_employee.is_seller?
            -# Returns
            %li
              = link_to (admin_sale_returns_path), class: "#{'active' if (controller_name == 'sales' && action_name == 'index_returns')}" do
                %i.fas.fa-undo
                = t("header.navigation.returns")
            -# End Returns

          - if current_employee.is_administrator? || current_employee.is_seller?
            -# Quotes
            %li
              = link_to (admin_price_lists_path), class: "#{'active' if (controller_name == 'price_lists')}" do
                %i.fas.fa-calculator
                = t("header.navigation.price_lists")
            -# End Quotes
      -# End Sales

    - if current_employee.is_administrator?
      -# Reports
      %li.dropdown
        %a.dropdown-toggle{"data-toggle": "dropdown", href: "#"}
          %i.fas.fa-chart-bar
          = t("header.navigation.reports")
          %i.fas.fa-caret-down

        %ul.dropdown-menu
          -# Purchases
          %li
            = link_to (admin_reports_purchases_path), class: "#{'active' if (controller_name == 'reports' && (action_name == 'purchases' || action_name == 'purchases_report')) }" do
              %i.fas.fa-shopping-bag
              = t("header.navigation.purchases")
          -# End purchases

          -# Sales
          %li
            = link_to (admin_reports_sales_path), class: "#{'active' if (controller_name == 'reports' && (action_name == 'sales' || action_name == 'sales_report')) }" do
              %i.fas.fa-shopping-cart
              = t("header.navigation.sales")
          -# End Sales
      -# End Reports

    - if current_employee.is_administrator?
      -# Employees
      %li
        = link_to (admin_employees_path), class: "#{'active' if controller_name == 'employees'}" do
          %i.fas.fa-briefcase
          %span= t("header.navigation.employees")
      -# End Employees

app/views/layouts/admin/_notifications.html.haml
- if current_employee.is_administrator? || current_employee.is_seller?

  .notifications-container
    - @noti_flag = true

    .dropdown
      %a{class: "custom-btn dropdown-toggle #{'with-noti' if (Notification.where(read_by: 'false').count > 0)}", "data-toggle": "dropdown", href: "#", "data-tooltip": "true", "data-placement": "left", title: t("header.navigation.notifications")}
        %i.fas.fa-bell
        -# Notification render_sync
        = sync partial: "notification_icon", collection: Notification.all
        = sync_new partial: "notification_icon", resource: Notification.new
        -# End Notification render_sync

      - if current_employee
        %ul{class: "dropdown-menu #{'no-noti' if (Notification.where(read_by: 'false').count < 1)}"}
          -# Notifications render_sync
          = sync partial: "notifications", collection: Notification.all
          = sync_new partial: "notifications", resource: Notification.new
          -# End Notifications render_sync

          - if (Notification.unread.count > 0)
            .noti.clean
              %li
                = link_to admin_clean_notifications_path(redirect_to: request.fullpath), method: "patch" do
                  %i.fas.fa-trash
                  %span
                    %b= t("sale.clean_notifications")

app/views/layouts/admin/_user.html.haml
.user-container
  .dropdown
    %a.custom-btn.dropdown-toggle{"data-toggle": "dropdown", href: "#", "data-tooltip": "true", "data-placement": "left", title: t("activerecord.models.user")}
      %i.fas.fa-user

    %ul.dropdown-menu
      - if current_employee
        -# Employee detail render_sync
        = sync partial: "employee_info", resource: current_employee
        -# = sync_new partial: "employee_info", resource: Employee.new
        -# End Employee detail render_sync

app/views/layouts/admin/application.html.haml
!!!
%html
  %head
    %title
      Better and Nice Produce Corp

    -# Meta information
    %meta{charset: "utf-8"}/
    %meta{content: "text/html;charset=utf-8", "http-equiv": "content-type"}/
    %meta{content: "IE=edge", "http-equiv": "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui", name: "viewport"}/
    %meta{content: "NOINDEX, NOFOLLOW", name: "ROBOTS"}/
    -# End Meta information

    -# Favicon settings
    = favicon_link_tag asset_path("img/favicon.png"), rel: "icon", type: "image/png"
    %meta{content: "#fef7f8", name: "theme-color"}/
    -# End Favicon settings

    -# OpenGraph info
    -# End OpenGraph info

    -# CSRF Tags
    = csrf_meta_tags
    -# End CSRF Tags

    -# CSP Tags
    = csp_meta_tag
    -# End CSP Tags

    -# Application assets
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = stylesheet_link_tag "admin", media: "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"
    =# javascript_include_tag "https://www.gstatic.com/charts/loader.js", "data-turbolinks-track": "reload"
    -# End Application assets

    -# Render sync config
    = include_sync_config
    -# End Render sync config

  %body{"data-locale": "#{I18n.locale}"}
    -# Render header
    = render "layouts/admin/header"
    -# End Render header

    -# Fix body (affix)
    .fix-body
    -# End Fix body (affix)

    -# Render alerts
    = render "layouts/admin/alerts"
    -# End Render alerts

    -# Preloader
    .preloader
      .spinner
        .bounce1
        .bounce2
        .bounce3
    -# End Preloader

    -# Main content
    = yield
    -# End Main content

    -# Render footer
    = render "layouts/admin/footer"
    -# End Render footer

    -# Material input script
    = javascript_include_tag "material-input", "data-turbolinks-track": "reload"
    -# End Material input script

    -# Form script
    = javascript_include_tag "form", "data-turbolinks-track": "reload"
    -# End Form script

    -# Barcode script
    = javascript_include_tag "barcode", "data-turbolinks-track": "reload"
    -# End Barcode script

app/views/layouts/admin/application_pdf.html.haml
!!!
%html
  %head
    %title Better and Nice Produce Corp
    -# Meta information
    %meta{charset: "utf-8"}/
    %meta{content: "text/html;charset=utf-8", "http-equiv": "content-type"}/
    %meta{content: "IE=edge", "http-equiv": "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui", name: "viewport"}/
    %meta{content: "NOINDEX, NOFOLLOW", name: "ROBOTS"}/
    -# End Meta information

    -# Base
    %base{href: "#{$banp_domain}"}/
    -# End Base

    -# Favicon and theme settings
    = favicon_link_tag asset_path("img/favicon.png"), rel: "icon", type: "image/png"
    %meta{content: "#444444", name: "theme-color"}/
    -# End Favicon and theme settings

    -# CSRF Tags
    = csrf_meta_tags
    -# End CSRF Tags

    -# CSP Tags
    = csp_meta_tag
    -# End CSP Tags

    -# PDF Stylesheet
    = wicked_pdf_stylesheet_link_tag "application"
    = wicked_pdf_stylesheet_link_tag "admin"
    -# End PDF Stylesheet

    -# Jquery & Barcode
    = javascript_include_tag "http://code.jquery.com/jquery-1.10.0.min.js"
    = javascript_include_tag "http://code.jquery.com/ui/1.10.3/jquery-ui.min.js"
    = javascript_include_tag "https://cdn.jsdelivr.net/npm/jsbarcode@3.11.0/dist/JsBarcode.all.min.js"

    -# Execute Script
    :javascript
      $(document).ready(function() {
        // Display Barcodes
        JsBarcode("#barcode").init();
      });

  %body.body-pdf
    -# Header
    %header#back-top.header-top
      %section.top-navbar.top-navbar-pdf
        .container
          .navbar-brand-top
            .row.navbar-brand-row
              .col-xs-4.logo-top
                %p.banp-logo BANP
              .col-xs-8.info-pdf
                %p= t('views.landing.motto')
    -# End Header

    -# Main content
    = yield
    -# End Main content