config/routes.rb
  post "/pay-upon-delivery/checkout", to: "pay_upon_delivery#checkout", as: "pay_upon_delivery_checkout"
  # End Pay upon delivery

  # Notifications
  get "/authentication/notifications", to: "authentication/notifications#index", as: "auth_notifications"
  # End Notifications

  # Customers
  get "/sign-up", to: "customers#new", as: "sign_up"
  get "/user", to: "customers#show", as: "customer"
  get "/user/edit", to: "customers#edit", as: "edit_customer"
  get "/users", to: redirect("/sign-up")
  post "/users", to: "customers#create", as: "customers"
  patch "/user", to: "customers#update", as: "update_customer"
  patch "/user/deactive", to: "customers#deactive", as: "deactive_customer"
  # End Customers

  # Users
  get "/user/update-password", to: "users#customer_update_password", as: "customer_update_password"
  patch "/user/update-password", to: "users#customer_change_password", as: "customer_change_password"
  # End Users

  # Sessions
  get "/sign-in", to: "authentication/sessions#new", as: "sign_in"
  get "/two-factor", to: "authentication/sessions#two_factor", as: "two_factor"
  post "/sign-in", to: "authentication/sessions#create", as: "sign_in_customer"
  post "/two-factor", to: "authentication/sessions#two_factor_auth", as: "two_factor_auth"
  patch "/resend-otp", to: "authentication/sessions#resend_otp", as: "resend_otp"
  delete "/sign-out", to: "authentication/sessions#destroy", as: "sign_out"
  # End Sessions

  # Confirmations
  get "/confirm-account", to: "authentication/confirmations#new", as: "confirm_account"
  get "/confirm-customer-account/:confirmation_token", to: "authentication/confirmations#show", as: "confirm_customer_account"
  post "/confirm-account", to: "authentication/confirmations#send_confirmation_email", as: "resend_confirmation"
  # End Confirmations

  # Unlocks
  get "/unlock-account", to: "authentication/unlocks#new", as: "unlock_account"
  get "/unlock-customer-account/:unlock_token", to: "authentication/unlocks#show", as: "unlock_customer_account"
  post "/unlock-account", to: "authentication/unlocks#send_unlock_email", as: "resend_unlock"
  # End Unlocks

  # Passwords
  get "/reset-password", to: "authentication/passwords#new", as: "reset_password"
  get "/reset-customer-password/:reset_password_token", to: "authentication/passwords#show", as: "reset_customer_password"
  post "/reset-password", to: "authentication/passwords#send_reset_password_email", as: "resend_reset_password"
  patch "/reset-customer-password", to: "authentication/passwords#update_password", as: "update_password"
  # End Passwords

  # End Authentications

  # Trackings
  get "/orders", to: "trackings#index", as: "orders"
  get "/tracking/:id", to: "trackings#show", as: "tracking"
  patch "/tracking/:id/confirm", to: "trackings#confirm_delivery", as: "confirm_delivery"
  # End Trackings

  # Invoices
  get "/invoice/:id", to: "invoices#show", as: "order_invoice"
  # End Invoices

  # Charts namespace
  namespace :charts do
    get "purchases-by-month", to: "purchases_by_month", as: "purchases_by_month"
    get "sales-by-month", to: "sales_by_month", as: "sales_by_month"

    get "sales-by-products", to: "sales_by_products", as: "sales_by_products"
    get "purchases-by-products", to: "purchases_by_products", as: "purchases_by_products"

    get "sales-by-customers", to: "sales_by_customers", as: "sales_by_customers"
    get "purchases-by-providers", to: "purchases_by_providers", as: "purchases_by_providers"

    get "sales-by-employees", to: "sales_by_employees", as: "sales_by_employees"
    get "purchases-by-employees", to: "purchases_by_employees", as: "purchases_by_employees"

    get "sales-by-categories", to: "sales_by_categories", as: "sales_by_categories"
    get "purchases-by-categories", to: "purchases_by_categories", as: "purchases_by_categories"

    get "products-by-categories", to: "products_by_categories", as: "products_by_categories"
  end
  # End Charts namespace

  # Admin namespace
  namespace :admin do
    # Root
    root "dashboard#index"
    # End Root

    # Authentications

    # Notifications
    get "/authentication/notifications", to: "authentication/notifications#index", as: "auth_notifications"
    # End Notifications

    # Sessions
    get "/sign-in", to: "authentication/sessions#new", as: "sign_in"
    get "/two-factor", to: "authentication/sessions#two_factor", as: "two_factor"
    post "/sign-in", to: "authentication/sessions#create", as: "sign_in_employee"
    post "/two-factor", to: "authentication/sessions#two_factor_auth", as: "two_factor_auth"
    patch "/resend-otp", to: "authentication/sessions#resend_otp", as: "resend_otp"
    delete "/sign-out", to: "authentication/sessions#destroy", as: "sign_out"
    # End Sessions

    # Confirmations
    get "/confirm-account", to: "authentication/confirmations#new", as: "confirm_account"
    get "/confirm-employee-account/:confirmation_token", to: "authentication/confirmations#show", as: "confirm_employee_account"
    post "/confirm-account", to: "authentication/confirmations#send_confirmation_email", as: "resend_confirmation"
    # End Confirmations

    # Unlocks
    get "/unlock-account", to: "authentication/unlocks#new", as: "unlock_account"
    get "/unlock-employee-account/:unlock_token", to: "authentication/unlocks#show", as: "unlock_employee_account"
    post "/unlock-account", to: "authentication/unlocks#send_unlock_email", as: "resend_unlock"
    # End Unlocks

    # Passwords
    get "/reset-password", to: "authentication/passwords#new", as: "reset_password"
    get "/reset-employee-password/:reset_password_token", to: "authentication/passwords#show", as: "reset_employee_password"
    post "/reset-password", to: "authentication/passwords#send_reset_password_email", as: "resend_reset_password"
    patch "/reset-employee-password", to: "authentication/passwords#update_password", as: "update_password"
    # End Passwords

    # End Authentications

    # Employees
    get "/employees", to: "employees#index", as: "employees"
    get "/employee/new", to: "employees#new", as: "new_employee"
    get "/employee/:id", to: "employees#show", as: "employee"
    get "/employee/:id/edit", to: "employees#edit", as: "edit_employee"
    get "/employee/:id/history", to: "employees#history", as: "history_employee"
    post "/employees", to: "employees#create"
    patch "/employee/:id", to: "employees#update", as: "update_employee"
    patch "/employees/:id/active", to: "employees#active", as: "active_employee"
    patch "/employees/:id/deactive", to: "employees#deactive", as: "deactive_employee"
    # End Employees

    # Employees/Users
    get "/employee/:id/create-user", to: "users#new_employee_user", as: "new_employee_user"
    get "/employee/:id/update-password", to: "users#employee_update_password", as: "update_password_employee"
    post "/employee/:id/create-user", to: "users#create_employee_user", as: "create_employee_user"
    patch "/employee/:id/update-password", to: "users#employee_change_password", as: "change_password_employee"
    # End Employees/Users

    # Providers
    get "/providers", to: "providers#index", as: "providers"
    get "/provider/new", to: "providers#new", as: "new_provider"
    get "/provider/:id", to: "providers#show", as: "provider"
    get "/provider/:id/edit", to: "providers#edit", as: "edit_provider"
    get "/provider/:id/history", to: "providers#history", as: "history_provider"
    post "/providers", to: "providers#create"
    patch "/provider/:id", to: "providers#update", as: "update_provider"
    patch "/providers/:id/active", to: "providers#active", as: "active_provider"
    patch "/providers/:id/deactive", to: "providers#deactive", as: "deactive_provider"
    # End Providers

    # Customers
    get "/customers", to: "customers#index", as: "customers"
    get "/customer/new", to: "customers#new", as: "new_customer"
    get "/customer/:id", to: "customers#show", as: "customer"
    get "/customer/:id/edit", to: "customers#edit", as: "edit_customer"
    get "/customer/:id/history", to: "customers#history", as: "history_customer"
    post "/customers", to: "customers#create"
    patch "/customer/:id", to: "customers#update", as: "update_customer"
    patch "/customers/:id/active", to: "customers#active", as: "active_customer"
    patch "/customers/:id/deactive", to: "customers#deactive", as: "deactive_customer"
    # End Customers

    # Customers/Users
    get "/customer/:id/create-user", to: "users#new_customer_user", as: "new_customer_user"
    get "/customer/:id/update-password", to: "users#customer_update_password", as: "update_password_customer"
    post "/customer/:id/create-user", to: "users#create_customer_user", as: "create_customer_user"
    patch "/customer/:id/update-password", to: "users#customer_change_password", as: "change_password_customer"
    # End Customers/Users

    # Categories
    get "/categories", to: "categories#index", as: "categories"
    get "/category/new", to: "categories#new", as: "new_category"
    get "/category/:id", to: "categories#show", as: "category"
    get "/category/:id/edit", to: "categories#edit", as: "edit_category"
    get "/category/:id/history", to: "categories#history", as: "history_category"
    post "/categories", to: "categories#create"
    patch "/category/:id", to: "categories#update", as: "update_category"
    patch "/categories/:id/active", to: "categories#active", as: "active_category"
    patch "/categories/:id/deactive", to: "categories#deactive", as: "deactive_category"
    # End Categories

    # Products
    get "/products", to: "products#index", as: "products"
    get "/product/new", to: "products#new", as: "new_product"
    get "/product/:id", to: "products#show", as: "product"
    get "/product/:id/edit", to: "products#edit", as: "edit_product"
    get "/product/:id/history", to: "products#history", as: "history_product"
    post "/products", to: "products#create"

app/models/provider.rb
class Provider < ApplicationRecord
  # Associations
  has_many :purchases
  # End Associations

  # Audit
  audited
  # End Audit

  # Render sync
  sync :all
  # End Render sync

  # Search
  def self.search(search, show_all)
    if search
      if show_all == "enabled-only"
        self.where("(name LIKE :search OR FEIN LIKE :search OR phone LIKE :search OR email LIKE :search OR address LIKE :search) AND (state = true)", search: "%#{search}%")

      else
        self.where("(name LIKE :search OR FEIN LIKE :search OR phone LIKE :search OR email LIKE :search OR address LIKE :search)", search: "%#{search}%")
      end

    elsif show_all == "all"
      all

    else
      enabled
    end
  end
  # End Search

  ## Friendly_ID

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  # Friendly_ID slug_candidates
  def slug_candidates
    [
      [:name],
      [:name, :FEIN, :id]
    ]
  end

  # Update Friendly_ID slug
  def should_generate_new_friendly_id?
    slug.blank? || name_changed? || FEIN_changed?
  end
  # End Update Friendly_ID slug

  ## End Friendly_ID

  # Active Storage
  has_one_attached :image
  # End Active Storage

  ## Validations

  # Uniqueness validation
  validates :FEIN, uniqueness: { case_sensitive: false }
  validates :email, uniqueness: { case_sensitive: false }
  validates :phone, uniqueness: { case_sensitive: false }
  # End Uniqueness validation

  # Presence validation
  validates :name, presence: true
  # End  Presence validation

  # Length validation
  validates :name, length: { maximum: 255 }
  validates :FEIN, length: { is: 10 }, allow_blank: true
  validates :email, length: { maximum: 255 }, allow_blank: true
  #   validates :phone, length: { is: 14 }, allow_blank: true
  validates :address, length: { maximum: 255 }, allow_blank: true
  # End Length validation

  # Type validation
  validate :correct_image_type
  # End Type validation

  # Validate file type
  def correct_image_type
    if image.attached? && !image.content_type.in?(%w(image/jpeg image/gif image/png))
      errors.add(:image, :blank, message: I18n.t("validates.image_format"))
    end
  end

  # Format validation
  validates_format_of :FEIN, with: /\A\d{2}-\d{7}\z/ ,allow_blank: true # 00-0000000
  #   validates_format_of :phone, with: /\A\(\d{3}\) \d{3}-\d{4}\z/ ,allow_blank: true # (000) 000-0000
  # End Format validation

  ## End Validations

  ## Scopes
  scope :enabled, -> { where(state: true) }
  ## End Scopes

  ## Callbacks

  # Before destroy
  before_destroy :not_permit_destroy

  # Before_destroy callback, avoid destroy information
  def not_permit_destroy
    false
  end

  ## End Callbacks
end

app/controllers/admin/providers_controller.rb
class Admin::ProvidersController < ApplicationController
  # Admin layout
  layout "admin/application"
  # End Admin layout

  # Find providers with Friendly_ID
  before_action :set_provider, only: [:show, :edit, :update, :active, :deactive, :history]
  # End Find providers with Friendly_ID

  # Sync model DSL
  enable_sync only: [:create, :update, :active, :deactive]
  # End Sync model DSL

  # Authentication
  before_action :require_employee, :require_administrator
  # End Authentication

  # Authentication
  before_action :require_warehouse_supervisor, only: [:index, :show]
  # End Authentication

  # Authentication
  skip_before_action :require_administrator, only: [:index, :show]
  # End Authentication

  # admin/providers
  def index
    @providers = Provider.search(params[:search], params[:show]).paginate(page: params[:page], per_page: 15) # Providers with pagination
    @show_all = params[:show] == "all" ? true : false # View All (Enabled and Disabled)
    @count = @providers.count

    # PDF view configuration
    current_lang = params[:lang]
    I18n.locale = current_lang

    datetime =  Time.zone.now
    file_time = datetime.strftime("%m%d%Y")

    name_pdf = "providers-#{file_time}"
    template = "admin/providers/index_pdf.html.haml"
    title_pdf = t("header.navigation.providers")
    # End PDF view configuration

    respond_to do |format|
      format.html
      format.js
      format.pdf do
        to_pdf(name_pdf, template, Provider.all, I18n.l(datetime), title_pdf)
      end
    end
  end

  # admin/provider/new
  def new
    @provider = Provider.new
  end

  # admin/provider/:id)
  def show
    # Provider found by before_action

    # PDF view configuration
    current_lang = params[:lang]
    I18n.locale = current_lang

    datetime =  Time.zone.now
    file_time = datetime.strftime("%m%d%Y")

    name_pdf = "provider-#{@provider.slug}-#{file_time}"
    template = "admin/providers/show_pdf.html.haml"
    title_pdf = t("activerecord.models.provider")
    # End PDF view configuration

    respond_to do |format|
      format.html
      format.pdf do
        to_pdf(name_pdf, template, @provider, I18n.l(datetime), title_pdf)
      end
    end
  end

  # admin/provider/:id/edit
  def edit
    # Provider found by before_action
  end

  # admin/provider/:id/history
  def history
    # Provider found by before_action

    @history = @provider.audits
  end

  # Create
  def create
    @provider = Provider.new(provider_params)

    # Deleting blank spaces
    @provider[:name] = @provider[:name].strip
    @provider[:FEIN] = @provider[:FEIN].strip
    @provider[:email] =  @provider[:email].strip.downcase
    @provider[:phone] = @provider[:phone].strip
    @provider[:address] = @provider[:address].strip
    # End Deleting blank spaces

    # If record was saved
    if @provider.save
      redirect_to [:admin, @provider], notice: t("alerts.created", model: t("activerecord.models.provider"))

      # If record was not saved
    else
      render :new
    end
  end

  # Update
  def update
    if @provider.update(provider_params)
      redirect_to [:admin, @provider], notice: t("alerts.updated", model: t("activerecord.models.provider"))

    else
      render :edit
    end
  end

  # Active
  def active
    if @provider.update(state: true)
      redirect_to admin_provider_path(@provider), notice: t("alerts.enabled", model: t("activerecord.models.provider"))

    else
      redirect_to admin_provider_path(@provider), notice: t("alerts.not_enabled", model: t("activerecord.models.provider"))
    end
  end

  # Deactive
  def deactive
    if @provider.update(state: false)
      redirect_to admin_provider_path(@provider), notice: t("alerts.disabled", model: t("activerecord.models.provider"))

    else
      redirect_to admin_provider_path(@provider), notice: t("alerts.not_disabled", model: t("activerecord.models.provider"))
    end
  end

  private

  # Set Provider
  def set_provider
    @provider = Provider.friendly.find(params[:id])

  rescue
    redirect_to admin_providers_path, alert: t("alerts.not_found", model: t("activerecord.models.provider"))
  end

  # Provider params
  def provider_params
    params.require(:provider).permit(:name, :FEIN, :email, :phone, :address, :image)
  end
end

app/views/sync/providers/_data_details.html.haml
-# Details
%section.details
  .container
    -# Title
    .row.title-container
      .col-xs-12.col-sm-6.col-md-8
        -# Heading
        %h1{class: "#{provider.state}"}
          %i.fas.fa-id-card
          = provider.name
        -# End Heading

      .col-xs-12.col-sm-6.col-md-4.text-right
        -# Export button
        .btn-container.inline
          = link_to (admin_provider_path(provider, format: "pdf", lang: I18n.locale)), target: "_blank", class: "btn btn-general" do
            %i.fas.fa-download
            %span= t("views.index.export")
        -# End Export button
    -# End Title

    -# Breadcrumb
    .row
      .col-xs-12.hidden-xs
        .breadcrumb-container
          %ol.breadcrumb
            %li
              = link_to (admin_root_path) do
                %i.fas.fa-tachometer-alt
                %span= t("header.navigation.dashboard")
            %li
              = link_to (admin_providers_path) do
                %i.fas.fa-list-alt
                %span= t("header.navigation.providers")
            %li.active
              %i.fas.fa-id-card
              = provider.name
    -# End Breadcrumb

    -# Information
    .row
      .col-xs-12.col-md-5.col-lg-4
        -# Material card
        %div{class: "material-card shadow-card #{provider.state}"}
          .row.no-margin
            .col-xs-12.no-padding
              .general-info
                -# Image
                .image-container
                  - if provider.image.attached?
                    = image_tag url_for(provider.image), class: "img-responsive"

                  - else
                    = image_tag url_for("https://res.cloudinary.com/reymundotenorio/image/upload/v1563544834/BANP/default.png"), class: "img-responsive"
                -# End Image

                .main-info
                  %p= t("views.show.created_at", time: time_ago_in_words(provider.created_at))
                  %p= t("views.show.updated_at", time: time_ago_in_words(provider.updated_at))

                .main-buttons
                  .col-xs-12.col-sm-4.col-md-6.button-container.no-padding
                    = link_to (admin_edit_provider_path(provider)), class: "btn btn-general" do
                      %i.fas.fa-edit
                      %span= t("views.show.edit")

                  .col-xs-12.col-sm-4.col-md-6.button-container.no-padding
                    = link_to (admin_history_provider_path(provider)), class: "btn btn-general" do
                      %i.fas.fa-history
                      %span= t("views.show.history")

                  .col-xs-12.col-sm-4.col-md-12.button-container.no-padding
                    - if provider.state
                      = link_to (admin_deactive_provider_path(provider)), method: "patch", class: "btn btn-general" do
                        %i.fas.fa-times
                        %span= t("views.show.disable")

                    - else
                      = link_to (admin_active_provider_path(provider)), method: "patch", class: "btn btn-general" do
                        %i.fas.fa-check
                        %span= t("views.show.enable")
        -# End Material card

      .col-xs-12.col-md-7.col-lg-8
        -# Material card
        %div{class: "material-card shadow-card #{provider.state}"}
          .row.no-margin
            .col-xs-12.no-padding
              %div{class: "detail-info #{provider.state}"}
                -# Set attributes
                - attributes = ["FEIN", "email" ,"phone", "address", "state"]

                - attributes.each do |attribute|
                  .info
                    %p.title
                      %b= t("activerecord.attributes.provider.#{attribute}")

                    - if attribute == "state"
                      %p= provider.state ? t("views.show.enabled") : t("views.show.disabled")

                    - else
                      %p= provider["#{attribute}"]
        -# End Material card
    -# End Information
-# End Details

app/views/sync/providers/_data_table.html.haml
%tr{class: "clickable-row #{provider.state}", "data-href": "#{admin_provider_path(provider)}"}
  -# Set attributes
  - attributes = ["name", "FEIN", "email" ,"phone"]

  %td
    = link_to admin_provider_path(provider), class: "record-link", "data-header": "No.", "data-toggle": "tooltip", "data-placement": "bottom", title: t("views.index.view_details") do
      %p= provider.id

  - attributes.each do |attribute|
    %td
      = link_to admin_provider_path(provider), class: "record-link", "data-header": t("activerecord.attributes.provider.#{attribute}"), "data-toggle": "tooltip", "data-placement": "bottom", title: t("views.index.view_details") do
        %p= provider["#{attribute}"]

app/views/sync/providers/_data_table_provider_name.html.haml
%p= provider.name

app/views/sync/providers/_detail_provider_name.html.haml
%p.text-right= provider.name

app/views/sync/providers/_select_provider.html.haml
%tr{class: "#{provider.state}"}
  -# Set attributes
  - attributes = ["name", "FEIN", "email", "phone"]

  %td
    %p= provider.id

  - attributes.each do |attribute|
    %td
      %p= provider["#{attribute}"]

  %td.align-middle
    %p
      = button_tag class: "btn btn-general select-provider", "data-id": provider.id, "data-name": "#{provider.name}", "data-toggle": "tooltip", "data-placement": "bottom", title: t("views.index.select") do
        %i.fas.fa-check