config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Change language
  get "/change-language/:lang", to: "settings#change_lang", as: "change_language"
  # End Change language

  # Errors pages
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  # Root
  root "landing#index"
  # End Root

  # Products
  get "/products", to: "products#index", as: "products"
  get "/product/:id", to: "products#show", as: "product"
  # End Products

  # Authentications

  # Cart
  get "/cart", to: "cart#index", as: "cart"
  # End Cart

  # Stripe
  get "/stripe/checkout", to: "stripe#payment", as: "stripe_payment"
  post "/stripe/checkout", to: "stripe#checkout", as: "stripe_checkout"
  # End Stripe

  # PayPal
  get "/paypal/payment", to: "paypal#paypal_payment", as: "paypal_payment"
  get "/paypal/sign-in", to: "paypal#paypal_sign_in", as: "paypal_sign_in"
  get "/paypal/checkout", to: "paypal#paypal_order", as: "paypal_order"
  post "/paypal/checkout", to: "paypal#paypal_checkout", as: "paypal_checkout"
  post "/paypal/sign-in", to: "paypal#paypal_auth", as: "paypal_auth"
  # End PayPal

  # Pay upon delivery
  get "/pay-upon-delivery/checkout", to: "pay_upon_delivery#payment", as: "pay_upon_delivery_payment"
  post "/pay-upon-delivery/checkout", to: "pay_upon_delivery#checkout", as: "pay_upon_delivery_checkout"
  # End Pay upon delivery

  # Notifications
  get "/authentication/notifications", to: "authentication/notifications#index", as: "auth_notifications"
  # End Notifications

  # Customers
  get "/sign-up", to: "customers#new", as: "sign_up"
  get "/user", to: "customers#show", as: "customer"
  get "/user/edit", to: "customers#edit", as: "edit_customer"
  get "/users", to: redirect("/sign-up")
  post "/users", to: "customers#create", as: "customers"
  patch "/user", to: "customers#update", as: "update_customer"
  patch "/user/deactive", to: "customers#deactive", as: "deactive_customer"
  # End Customers

  # Users
  get "/user/update-password", to: "users#customer_update_password", as: "customer_update_password"
  patch "/user/update-password", to: "users#customer_change_password", as: "customer_change_password"
  # End Users

  # Sessions
  get "/sign-in", to: "authentication/sessions#new", as: "sign_in"
  get "/two-factor", to: "authentication/sessions#two_factor", as: "two_factor"
  post "/sign-in", to: "authentication/sessions#create", as: "sign_in_customer"
  post "/two-factor", to: "authentication/sessions#two_factor_auth", as: "two_factor_auth"
  patch "/resend-otp", to: "authentication/sessions#resend_otp", as: "resend_otp"
  delete "/sign-out", to: "authentication/sessions#destroy", as: "sign_out"
  # End Sessions

  # Confirmations
  get "/confirm-account", to: "authentication/confirmations#new", as: "confirm_account"
  get "/confirm-customer-account/:confirmation_token", to: "authentication/confirmations#show", as: "confirm_customer_account"
  post "/confirm-account", to: "authentication/confirmations#send_confirmation_email", as: "resend_confirmation"
  # End Confirmations

  # Unlocks
  get "/unlock-account", to: "authentication/unlocks#new", as: "unlock_account"
  get "/unlock-customer-account/:unlock_token", to: "authentication/unlocks#show", as: "unlock_customer_account"
  post "/unlock-account", to: "authentication/unlocks#send_unlock_email", as: "resend_unlock"
  # End Unlocks

  # Passwords
  get "/reset-password", to: "authentication/passwords#new", as: "reset_password"
  get "/reset-customer-password/:reset_password_token", to: "authentication/passwords#show", as: "reset_customer_password"
  post "/reset-password", to: "authentication/passwords#send_reset_password_email", as: "resend_reset_password"
  patch "/reset-customer-password", to: "authentication/passwords#update_password", as: "update_password"
  # End Passwords

  # End Authentications

  # Trackings
  get "/orders", to: "trackings#index", as: "orders"
  get "/tracking/:id", to: "trackings#show", as: "tracking"
  patch "/tracking/:id/confirm", to: "trackings#confirm_delivery", as: "confirm_delivery"
  # End Trackings

  # Invoices
  get "/invoice/:id", to: "invoices#show", as: "order_invoice"
  # End Invoices

  # Charts namespace
  namespace :charts do
    get "purchases-by-month", to: "purchases_by_month", as: "purchases_by_month"
    get "sales-by-month", to: "sales_by_month", as: "sales_by_month"

    get "sales-by-products", to: "sales_by_products", as: "sales_by_products"
    get "purchases-by-products", to: "purchases_by_products", as: "purchases_by_products"

    get "sales-by-customers", to: "sales_by_customers", as: "sales_by_customers"
    get "purchases-by-providers", to: "purchases_by_providers", as: "purchases_by_providers"

    get "sales-by-employees", to: "sales_by_employees", as: "sales_by_employees"
    get "purchases-by-employees", to: "purchases_by_employees", as: "purchases_by_employees"

    get "sales-by-categories", to: "sales_by_categories", as: "sales_by_categories"
    get "purchases-by-categories", to: "purchases_by_categories", as: "purchases_by_categories"

    get "products-by-categories", to: "products_by_categories", as: "products_by_categories"
  end
  # End Charts namespace

  # Admin namespace
  namespace :admin do
    # Root
    root "dashboard#index"
    # End Root

    # Authentications

    # Notifications
    get "/authentication/notifications", to: "authentication/notifications#index", as: "auth_notifications"
    # End Notifications

    # Sessions
    get "/sign-in", to: "authentication/sessions#new", as: "sign_in"
    get "/two-factor", to: "authentication/sessions#two_factor", as: "two_factor"
    post "/sign-in", to: "authentication/sessions#create", as: "sign_in_employee"
    post "/two-factor", to: "authentication/sessions#two_factor_auth", as: "two_factor_auth"
    patch "/resend-otp", to: "authentication/sessions#resend_otp", as: "resend_otp"
    delete "/sign-out", to: "authentication/sessions#destroy", as: "sign_out"
    # End Sessions

    # Confirmations
    get "/confirm-account", to: "authentication/confirmations#new", as: "confirm_account"
    get "/confirm-employee-account/:confirmation_token", to: "authentication/confirmations#show", as: "confirm_employee_account"
    post "/confirm-account", to: "authentication/confirmations#send_confirmation_email", as: "resend_confirmation"
    # End Confirmations

    # Unlocks
    get "/unlock-account", to: "authentication/unlocks#new", as: "unlock_account"
    get "/unlock-employee-account/:unlock_token", to: "authentication/unlocks#show", as: "unlock_employee_account"
    post "/unlock-account", to: "authentication/unlocks#send_unlock_email", as: "resend_unlock"
    # End Unlocks

    # Passwords
    get "/reset-password", to: "authentication/passwords#new", as: "reset_password"
    get "/reset-employee-password/:reset_password_token", to: "authentication/passwords#show", as: "reset_employee_password"
    post "/reset-password", to: "authentication/passwords#send_reset_password_email", as: "resend_reset_password"
    patch "/reset-employee-password", to: "authentication/passwords#update_password", as: "update_password"
    # End Passwords

    # End Authentications

    # Employees
    get "/employees", to: "employees#index", as: "employees"
    get "/employee/new", to: "employees#new", as: "new_employee"
    get "/employee/:id", to: "employees#show", as: "employee"
    get "/employee/:id/edit", to: "employees#edit", as: "edit_employee"
    get "/employee/:id/history", to: "employees#history", as: "history_employee"
    post "/employees", to: "employees#create"
    patch "/employee/:id", to: "employees#update", as: "update_employee"
    patch "/employees/:id/active", to: "employees#active", as: "active_employee"
    patch "/employees/:id/deactive", to: "employees#deactive", as: "deactive_employee"
    # End Employees

    # Employees/Users
    get "/employee/:id/create-user", to: "users#new_employee_user", as: "new_employee_user"
    get "/employee/:id/update-password", to: "users#employee_update_password", as: "update_password_employee"
    post "/employee/:id/create-user", to: "users#create_employee_user", as: "create_employee_user"
    patch "/employee/:id/update-password", to: "users#employee_change_password", as: "change_password_employee"
    # End Employees/Users

    # Providers
    get "/providers", to: "providers#index", as: "providers"
    get "/provider/new", to: "providers#new", as: "new_provider"
    get "/provider/:id", to: "providers#show", as: "provider"
    get "/provider/:id/edit", to: "providers#edit", as: "edit_provider"
    get "/provider/:id/history", to: "providers#history", as: "history_provider"
    post "/providers", to: "providers#create"
    patch "/provider/:id", to: "providers#update", as: "update_provider"
    patch "/providers/:id/active", to: "providers#active", as: "active_provider"
    patch "/providers/:id/deactive", to: "providers#deactive", as: "deactive_provider"
    # End Providers

    # Customers
    get "/customers", to: "customers#index", as: "customers"
    get "/customer/new", to: "customers#new", as: "new_customer"
    get "/customer/:id", to: "customers#show", as: "customer"
    get "/customer/:id/edit", to: "customers#edit", as: "edit_customer"
    get "/customer/:id/history", to: "customers#history", as: "history_customer"
    post "/customers", to: "customers#create"
    patch "/customer/:id", to: "customers#update", as: "update_customer"
    patch "/customers/:id/active", to: "customers#active", as: "active_customer"
    patch "/customers/:id/deactive", to: "customers#deactive", as: "deactive_customer"
    # End Customers

    # Customers/Users
    get "/customer/:id/create-user", to: "users#new_customer_user", as: "new_customer_user"

app/views/admin/partials/_authentication_messages.html.haml
%section.message
  .container
    .row
      .col-xs-12.col-sm-10.col-sm-offset-1.col-md-8.col-md-offset-2
        -# Material card
        .material-card.shadow-card
          .row.no-margin
            -# Flash notifications
            = render "admin/partials/authentication_flash"
            -# End Flash notifications

            .col-xs-12.no-padding.redirect-container
              -# Not found - back to home
              - if @source == "not-found"
                %p
                  = link_to (admin_root_path), title: "t('views.errors.back_to_home')" do
                    %i.fas.fa-undo-alt
                    %span= t("views.errors.back_to_home")

                -# Confirmation resend instructions
              - elsif @source == "confirmation"
                %p
                  = link_to (admin_confirm_account_path), title: "t('views.authentication.resend_instructions')" do
                    %i.fas.fa-envelope
                    %span= t("views.authentication.resend_instructions")

                -# Unlock resend instructions
              - elsif @source == "unlock"
                %p
                  = link_to (admin_unlock_account_path), title: "t('views.authentication.resend_instructions')" do
                    %i.fas.fa-envelope
                    %span= t("views.authentication.resend_instructions")

                -# Reset password resend instructions
              - elsif @source == "reset-password"
                %p
                  = link_to (admin_reset_password_path), title: "t('views.authentication.resend_instructions')" do
                    %i.fas.fa-envelope
                    %span= t("views.authentication.resend_instructions")
        -# End Material card

app/views/admin/partials/_details_info.html.haml
.col-xs-4
  -# Material card
  %div{class: "material-card material-card-pdf shadow-card shadow-card-pdf #{resource.state}"}
    .row.no-margin
      .col-xs-12.no-padding
        -# General information
        .general-info
          -# Image
          .image-container
            - if resource.image.attached?
              = image_tag url_for(resource.image), class: "img-responsive"
            - else
              = image_tag url_for("https://s3.amazonaws.com/betterandnice/images/default/default.png"), class: "img-responsive"
          -# End Image
        -# End General information
  -# End Material card

.col-xs-8
  -# Material card
  %div{class: "material-card material-card-pdf shadow-card shadow-card-pdf #{resource.state}"}
    .row.no-margin
      .col-xs-12.no-padding
        %div{class: "detail-info #{resource.state}"}
          - attributes.each do |attribute|
            .info
              %p.title
                %b= t("activerecord.attributes.#{resource}.#{attribute}")

              - if attribute == "state"
                %p= resource["#{attribute}"] ? t("views.show.enabled") : t("views.show.disabled")

              - else
                %p= resource["#{attribute}"]

          -# Setting user attributes
          - user_attributes = ["confirmed", "sign_in_count", "current_sign_in_at", "current_sign_in_ip", "last_sign_in_at", "last_sign_in_ip"]

          -# Display user attributes
          - if resource.user.present?
            - user_attributes.each do |attribute|
              .info
                %p.title
                  %b= t("activerecord.attributes.user.#{attribute}")

                - if attribute == "confirmed"
                  %p= resource.user["#{attribute}"] ? t("views.show.confirmed") : t("views.show.not_confirmed")

                - elsif attribute == "current_sign_in_at" || attribute == "last_sign_in_at"
                  %p= format_datetime(resource.user["#{attribute}"])

                - else
                  %p= resource.user["#{attribute}"]
          -# End Display user attributes
  -# End Material card

app/views/admin/partials/_table_information.html.haml
%tr{class: "#{resource.state}"}
  %td
    %p= resource.id
    
  - attributes.each do |attribute|
    %td
      %p= resource["#{attribute}"]